#define INFLUXDB_URL "INFLUXDB_URL"
#define INFLUXDB_TOKEN "INFLUXDB_TOKEN"
#define INFLUXDB_ORG "INFLUXDB_ORG"
#define INFLUXDB_BUCKET "INFLUXDB_BUCKET"
#define TZ_INFO "America/Sao_Paulo"
#define SEALEVELPRESSURE_HPA (1013.25)
const char *AP_SSID = "AP_SSID";
const char *AP_PWD = "AP_PWD";
